#version: '3.8'

services:
  flexreactphp:  # 여기를 'release'에서 'flexreactphp'로 변경
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flexreactphp
    ports:
      - "8888:80"
    networks:
      - flexreactphp-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 4G
        # reservations:
        #   cpus: 0.2
        #   memory: 2G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    restart: always
    depends_on:
      flexreactphp-mysql:
        condition: service_healthy
      flexreactphp-postgres:
        condition: service_healthy

  flexreactphp-mysql:
    image: mysql:8.0
    container_name: flexreactphp-mysql
    command: --default-authentication-plugin=caching_sha2_password --server-id=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init-mysql:/etc/mysql/conf.d/mysql.cnf
      - flexreactphp-mysql-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 2G
        # reservations:
        #   cpus: 0.2
        #   memory: 1G
    ports:
      - "3336:3306"
    networks:
      - flexreactphp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  flexreactphp-postgres:
    image: postgres:13
    container_name: flexreactphp-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d
      - flexreactphp-postgres-data:/var/lib/postgresql/data
    mem_limit: 2G
    cpus: 0.2
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 2G
        # reservations:
        #   cpus: 0.2
        #   memory: 1G
    ports:
      - "54320:5432"
    networks:
      - flexreactphp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 3

  flexreactphp-couchdb:
    image: couchdb:3.1.1
    container_name: flexreactphp-couchdb
    environment:
      - COUCHDB_USER=${DB_USER}
      - COUCHDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - flexreactphp-couchdb-data:/opt/couchdb/data
    ports:
      - "59840:5984"
    networks:
      - flexreactphp-network
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 2G
        # reservations:
        #   cpus: 0.1
        #   memory: 1G
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  flexreactphp-network:
    driver: bridge

volumes:
  flexreactphp-mysql-data:
  flexreactphp-postgres-data:
  flexreactphp-couchdb-data: